### PR TITLE
Missing Contact

### LINKED ISSUE #17: Renewals failing due to missing `contact` key
Didn't have time to investigate today, but filing this in case someone else runs into it too: seems like the ACME service is no longer providing a `contact` key in its response? This unfortunately causes renewals to fail.

```
Error refreshing certificate: keyNotFound(CodingKeys(stringValue: "contact", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"contact\", intValue: nil) (\"contact\").", underlyingError: nil))
```

I'll likely look into this more in ~24h as it will be production blocking very, very soon 😅 (glad my staging server caught it first!)

### PR DESCRIPTION
**Pull request by dimitribouniol**
The account object now seems to look like this as of ~June 10th, preventing renewals from being proceeding, so I've made the `contact` field optional as the spec suggests it should be. I haven't however found a spec that specifies the `key` and `createdAt` keys, so it's perfectly likely this changes again in the future 😅
```
{
   "key": {
     "kty": "EC",
     "crv": "P-256",
     "x": "...",
     "y": "..."
   },
   "createdAt": "2024-01-10T14:55:46Z",
   "status": "valid"
}
```

Also spotted some opportunities for other minor improvements, but I can pull those out into separate PRs if you prefer.

Fixes #17

### CODE REVIEW

File: Sources/AcmeSwift/Models/Account/AcmeAccountInfo.swift [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import Foundation
-import JWTKit
+@preconcurrency import JWTKit
```
Comment (m-barthelemy) [inline Sources/AcmeSwift/Models/Account/AcmeAccountInfo.swift]: oh what's the issue with JWTKit here?

**Review by m-barthelemy — COMMENTED** [review]
Thanks for the PR. Just wondering about the JWTKit change

File: Sources/AcmeSwift/Models/Account/AcmeAccountInfo.swift (hunk 1 above)
Comment (dimitribouniol) [reply Sources/AcmeSwift/Models/Account/AcmeAccountInfo.swift]: It gave me a build warning on the latest stable Xcode, which this silences.

Comment (m-barthelemy) [reply Sources/AcmeSwift/Models/Account/AcmeAccountInfo.swift]: I'm way out of my depth when it comes to all the sendable and concurrency stuff, but wouldn't it be safer overall to leave this as-is, assuming the JWTKit project will address the underlying issue at some point?

Comment (dimitribouniol) [reply Sources/AcmeSwift/Models/Account/AcmeAccountInfo.swift]: This just silences the warnings in this project - it doesn’t change any of the underlying behavior.

That said, I realized my clone must be locked to v4 which is why I saw the warning - let me see if re-cloning brings me to v5 and gets rid of it!

**Review by m-barthelemy — APPROVED** [review]
Thanks a lot!
